import { describe, expect, it } from "vitest"

describe("workspace package boundaries", () => {
  it("exports core, solid, and core-widgets entrypoints", async () => {
    const core = await import("@qt-solid/core")
    const coreNative = await import("@qt-solid/core/native")
    const coreWidgetLibrary = await import("@qt-solid/core/widget-library")
    const solid = await import("@qt-solid/solid")
    const solidVite = await import("@qt-solid/solid/vite")
    const solidRolldown = await import("@qt-solid/solid/rolldown")
    const solidHmr = await import("@qt-solid/solid/hmr")
    const solidCompiler = await import("@qt-solid/solid/compiler")
    const solidCompilerRt = await import("@qt-solid/solid/compiler-rt")
    const widgets = await import("@qt-solid/core-widgets")
    const widgetLibrary = await import("@qt-solid/core-widgets/widget-library")
    const exampleWidgetLibrary = await import("@qt-solid/example-widgets/widget-library")
    const exampleNative = await import("@qt-solid/example-widgets/native")

    expect(typeof core.QtApp.start).toBe("function")
    expect("QtBanner" in coreNative).toBe(false)
    expect(typeof coreWidgetLibrary.registerQtWidgetLibrary).toBe("function")
    expect(typeof coreWidgetLibrary.registerQtWidgetLibraryEntry).toBe("function")
    expect(typeof solid.createApp).toBe("function")
    expect(typeof solid.defineIntrinsicComponent).toBe("function")
    expect("createComponent" in solid).toBe(false)
    expect("setProp" in solid).toBe(false)
    expect(typeof solidVite.createQtSolidVitePlugin).toBe("function")
    expect(typeof solidRolldown.createQtSolidRolldownPlugin).toBe("function")
    expect(typeof solidHmr.mountOrReplaceQtSolidDevApp).toBe("function")
    expect(typeof solidCompiler.transformQtSolidModule).toBe("function")
    expect(typeof solidCompilerRt.createComponent).toBe("function")
    expect(typeof solidCompilerRt.setProp).toBe("function")
    expect(typeof solidCompilerRt.withQtSourceMeta).toBe("function")
    expect(widgets.intrinsicKind.window).toBe("window")
    expect(typeof widgetLibrary.registerCoreWidgetsLibrary).toBe("function")
    expect(typeof widgetLibrary.registerQtSolidWidgetLibrary).toBe("function")
    expect(widgetLibrary.qtWidgetLibrary).toBe(widgetLibrary.coreWidgetsLibrary)
    expect(widgetLibrary.qtWidgetLibraryEntry).toBe(widgetLibrary.coreWidgetsLibraryEntry)
    expect(typeof widgetLibrary.qtWidgetNativeBridge.entityMap.window?.create).toBe("function")
    expect(exampleWidgetLibrary.exampleWidgetsLibrary.metadata.kinds[0]?.intrinsicName).toBe("banner")
    expect(typeof exampleNative.QtBanner.create).toBe("function")
    expect(widgetLibrary.coreWidgetsLibrary.metadata.kinds[0]?.intrinsicName).toBe("button")
    expect(widgetLibrary.coreWidgetsLibraryEntry.nativeBridge).toBe(widgetLibrary.qtWidgetNativeBridge)
  })
})
