// Auto-generated by packages/core-native/crates/native/src/bin/generate_ts_bindings.rs. Do not edit.
import type { QtApp, QtInitialProp, QtNode } from "@qt-solid/core/native"

declare abstract class QtWidgetEntity {
  static create(app: QtApp): unknown
  __qtAttach?(initialProps: QtInitialProp[]): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
}

export declare class QtWindow extends QtWidgetEntity {
  static create(app: QtApp): QtWindow
  setAlignItems(value: "flex-start" | "center" | "flex-end" | "stretch"): void
  setAlwaysOnTop(value: boolean): void
  setDirection(value: "column" | "row"): void
  setEnabled(value: boolean): void
  setFrameless(value: boolean): void
  setGap(value: number): void
  setGrow(value: number): void
  setHeight(value: number): void
  setJustifyContent(value: "flex-start" | "center" | "flex-end"): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setNextFrameRequested(value: boolean): void
  setPadding(value: number): void
  setShrink(value: number): void
  setTick(value: boolean): void
  setTitle(value: string): void
  setTransparentBackground(value: boolean): void
  setVisible(value: boolean): void
  setWidth(value: number): void
  getDeltaMs(): number
  getElapsedMs(): number
  getNextFrameRequested(): boolean
  getSeq(): number
}

export declare class QtView extends QtWidgetEntity {
  static create(app: QtApp): QtView
  setAlignItems(value: "flex-start" | "center" | "flex-end" | "stretch"): void
  setDirection(value: "column" | "row"): void
  setEnabled(value: boolean): void
  setGap(value: number): void
  setGrow(value: number): void
  setHeight(value: number): void
  setJustifyContent(value: "flex-start" | "center" | "flex-end"): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPadding(value: number): void
  setShrink(value: number): void
  setWidth(value: number): void
}

export declare class QtGroup extends QtWidgetEntity {
  static create(app: QtApp): QtGroup
  setAlignItems(value: "flex-start" | "center" | "flex-end" | "stretch"): void
  setDirection(value: "column" | "row"): void
  setEnabled(value: boolean): void
  setGap(value: number): void
  setGrow(value: number): void
  setHeight(value: number): void
  setJustifyContent(value: "flex-start" | "center" | "flex-end"): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPadding(value: number): void
  setShrink(value: number): void
  setTitle(value: string): void
  setWidth(value: number): void
}

export declare class QtLabel extends QtWidgetEntity {
  static create(app: QtApp): QtLabel
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: number): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: number): void
  setWidth(value: number): void
}

export declare class QtButton extends QtWidgetEntity {
  static create(app: QtApp): QtButton
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: number): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: number): void
  setWidth(value: number): void
}

export declare class QtCanvas extends QtWidgetEntity {
  static create(app: QtApp): QtCanvas
  setEnabled(value: boolean): void
  setGrow(value: number): void
  setHeight(value: number): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setShrink(value: number): void
  setWidth(value: number): void
}

export declare class QtInput extends QtWidgetEntity {
  static create(app: QtApp): QtInput
  setAutoFocus(value: boolean): void
  setCursorPosition(value: number): void
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setFocusPolicy(value: "no-focus" | "tab-focus" | "click-focus" | "strong-focus"): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPlaceholder(value: string): void
  setPointSize(value: number): void
  setSelectionEnd(value: number): void
  setSelectionStart(value: number): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: number): void
  setWidth(value: number): void
  focus(): void
  selectAll(): void
}

export declare class QtCheck extends QtWidgetEntity {
  static create(app: QtApp): QtCheck
  setChecked(value: boolean): void
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: number): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: number): void
  setWidth(value: number): void
}

export declare class QtText extends QtWidgetEntity {
  static create(app: QtApp): QtText
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: number): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: number): void
  setWidth(value: number): void
}

export declare class QtSlider extends QtWidgetEntity {
  static create(app: QtApp): QtSlider
  setAutoFocus(value: boolean): void
  setEnabled(value: boolean): void
  setFocusPolicy(value: "no-focus" | "tab-focus" | "click-focus" | "strong-focus"): void
  setGrow(value: number): void
  setHeight(value: number): void
  setMaximum(value: number): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setMinimum(value: number): void
  setPageStep(value: number): void
  setShrink(value: number): void
  setStep(value: number): void
  setValue(value: number): void
  setWidth(value: number): void
}

export declare class QtDoubleSpinBox extends QtWidgetEntity {
  static create(app: QtApp): QtDoubleSpinBox
  setAutoFocus(value: boolean): void
  setEnabled(value: boolean): void
  setFocusPolicy(value: "no-focus" | "tab-focus" | "click-focus" | "strong-focus"): void
  setGrow(value: number): void
  setHeight(value: number): void
  setMaximum(value: number): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setMinimum(value: number): void
  setShrink(value: number): void
  setStep(value: number): void
  setValue(value: number): void
  setWidth(value: number): void
}
