// Auto-generated by packages/core-native/crates/native/src/bin/generate_ts_bindings.rs. Do not edit.

import type {
  AlignItems,
  FlexDirection,
  FocusPolicy,
  JustifyContent,
  QtApp,
  QtNode,
} from "@qt-solid/core/native"

import type {
  QtWidgetEntityCtor,
} from "@qt-solid/core/widget-library"

import {
  QtButton,
  QtCanvas,
  QtCheck,
  QtDoubleSpinBox,
  QtGroup,
  QtInput,
  QtLabel,
  QtSlider,
  QtText,
  QtView,
  QtWindow,
} from "@qt-solid/core-widgets/native"

import {
  asBoolean,
  asF64,
  asI32,
  asNonNegativeF64,
  asNonNegativeI32,
  asString,
  createEnumValueParser,
  type EventExportSpec,
  type PropLeafBinding as SharedPropLeafBinding,
  type QtWidgetBinding as SharedQtWidgetBinding,
} from "@qt-solid/core/qt-host.shared"

export type PropMethodName = "setAlignItems" | "setAlwaysOnTop" | "setAutoFocus" | "setChecked" | "setCursorPosition" | "setDirection" | "setEnabled" | "setFamily" | "setFocusPolicy" | "setFrameless" | "setGap" | "setGrow" | "setHeight" | "setItalic" | "setJustifyContent" | "setMaximum" | "setMinHeight" | "setMinWidth" | "setMinimum" | "setNextFrameRequested" | "setPadding" | "setPageStep" | "setPlaceholder" | "setPointSize" | "setSelectionEnd" | "setSelectionStart" | "setShrink" | "setStep" | "setText" | "setTick" | "setTitle" | "setTransparentBackground" | "setValue" | "setVisible" | "setWeight" | "setWidth"

export type PropLeafBinding = SharedPropLeafBinding<PropMethodName>
export type QtWidgetBinding = SharedQtWidgetBinding<PropMethodName>

const ALIGN_ITEMS_VALUES = ["flex-start", "center", "flex-end", "stretch"] as const

const asAlignItemsValue = createEnumValueParser<AlignItems>(ALIGN_ITEMS_VALUES)

const FLEX_DIRECTION_VALUES = ["column", "row"] as const

const asFlexDirectionValue = createEnumValueParser<FlexDirection>(FLEX_DIRECTION_VALUES)

const FOCUS_POLICY_VALUES = ["no-focus", "tab-focus", "click-focus", "strong-focus"] as const

const asFocusPolicyValue = createEnumValueParser<FocusPolicy>(FOCUS_POLICY_VALUES)

const JUSTIFY_CONTENT_VALUES = ["flex-start", "center", "flex-end"] as const

const asJustifyContentValue = createEnumValueParser<JustifyContent>(JUSTIFY_CONTENT_VALUES)

export const eventExportSpecs = {
  onChanged: {
    exportId: 7,
    payloadKind: "string",
    payloadFields: [
    ],
    echoes: [
      { propKey: "text", valueKind: "string", valuePath: "" },
    ],
  },
  onClicked: {
    exportId: 2,
    payloadKind: "unit",
    payloadFields: [
    ],
    echoes: [
    ],
  },
  onCloseRequested: {
    exportId: 1,
    payloadKind: "unit",
    payloadFields: [
    ],
    echoes: [
    ],
  },
  onCursorPositionChanged: {
    exportId: 5,
    payloadKind: "object",
    payloadFields: [
      { key: "oldPosition", valueKind: "number", valuePath: "oldPosition" },
      { key: "cursorPosition", valueKind: "number", valuePath: "cursorPosition" },
    ],
    echoes: [
      { propKey: "cursorPosition", valueKind: "number", valuePath: "cursorPosition" },
    ],
  },
  onFocusIn: {
    exportId: 3,
    payloadKind: "unit",
    payloadFields: [
    ],
    echoes: [
    ],
  },
  onFocusOut: {
    exportId: 4,
    payloadKind: "unit",
    payloadFields: [
    ],
    echoes: [
    ],
  },
  onSelectionChanged: {
    exportId: 6,
    payloadKind: "object",
    payloadFields: [
      { key: "selectionStart", valueKind: "number", valuePath: "selectionStart" },
      { key: "selectionEnd", valueKind: "number", valuePath: "selectionEnd" },
    ],
    echoes: [
      { propKey: "selectionStart", valueKind: "number", valuePath: "selectionStart" },
      { propKey: "selectionEnd", valueKind: "number", valuePath: "selectionEnd" },
    ],
  },
  onTextChanged: {
    exportId: 8,
    payloadKind: "string",
    payloadFields: [
    ],
    echoes: [
      { propKey: "text", valueKind: "string", valuePath: "" },
    ],
  },
  onToggled: {
    exportId: 9,
    payloadKind: "boolean",
    payloadFields: [
    ],
    echoes: [
      { propKey: "checked", valueKind: "boolean", valuePath: "" },
    ],
  },
  onValueChanged: {
    exportId: 10,
    payloadKind: "number",
    payloadFields: [
    ],
    echoes: [
      { propKey: "value", valueKind: "number", valuePath: "" },
    ],
  },
} as const satisfies Record<string, EventExportSpec>

export const widgetBindings = {
  "window": {
    props: {
      alignItems: { key: "alignItems", propId: 1, valueKind: "enum", reset: "stretch", method: "setAlignItems", parseValue(value, key) { return asAlignItemsValue(value, key); } },
      alwaysOnTop: { key: "alwaysOnTop", propId: 2, valueKind: "boolean", reset: false, method: "setAlwaysOnTop", parseValue(value, key) { return asBoolean(value, key); } },
      direction: { key: "direction", propId: 3, valueKind: "enum", reset: "column", method: "setDirection", parseValue(value, key) { return asFlexDirectionValue(value, key); } },
      enabled: { key: "enabled", propId: 4, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      frameless: { key: "frameless", propId: 5, valueKind: "boolean", reset: false, method: "setFrameless", parseValue(value, key) { return asBoolean(value, key); } },
      gap: { key: "gap", propId: 6, valueKind: "integer", reset: 0, method: "setGap", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      grow: { key: "grow", propId: 7, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 8, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      justifyContent: { key: "justifyContent", propId: 9, valueKind: "enum", reset: "flex-start", method: "setJustifyContent", parseValue(value, key) { return asJustifyContentValue(value, key); } },
      minHeight: { key: "minHeight", propId: 10, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 11, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      nextFrameRequested: { key: "nextFrameRequested", valueKind: "boolean", method: "setNextFrameRequested", parseValue(value, key) { return asBoolean(value, key); } },
      padding: { key: "padding", propId: 12, valueKind: "integer", reset: 0, method: "setPadding", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      shrink: { key: "shrink", propId: 13, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      tick: { key: "tick", valueKind: "boolean", method: "setTick", parseValue(value, key) { return asBoolean(value, key); } },
      title: { key: "title", propId: 14, valueKind: "string", method: "setTitle", parseValue(value, key) { return asString(value, key); } },
      transparentBackground: { key: "transparentBackground", propId: 15, valueKind: "boolean", reset: false, method: "setTransparentBackground", parseValue(value, key) { return asBoolean(value, key); } },
      visible: { key: "visible", propId: 16, valueKind: "boolean", reset: true, method: "setVisible", parseValue(value, key) { return asBoolean(value, key); } },
      width: { key: "width", propId: 17, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "view": {
    props: {
      alignItems: { key: "alignItems", propId: 1, valueKind: "enum", reset: "stretch", method: "setAlignItems", parseValue(value, key) { return asAlignItemsValue(value, key); } },
      direction: { key: "direction", propId: 2, valueKind: "enum", reset: "column", method: "setDirection", parseValue(value, key) { return asFlexDirectionValue(value, key); } },
      enabled: { key: "enabled", propId: 3, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      gap: { key: "gap", propId: 4, valueKind: "integer", reset: 0, method: "setGap", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      grow: { key: "grow", propId: 5, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 6, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      justifyContent: { key: "justifyContent", propId: 7, valueKind: "enum", reset: "flex-start", method: "setJustifyContent", parseValue(value, key) { return asJustifyContentValue(value, key); } },
      minHeight: { key: "minHeight", propId: 8, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 9, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      padding: { key: "padding", propId: 10, valueKind: "integer", reset: 0, method: "setPadding", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      shrink: { key: "shrink", propId: 11, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 12, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "group": {
    props: {
      alignItems: { key: "alignItems", propId: 1, valueKind: "enum", reset: "stretch", method: "setAlignItems", parseValue(value, key) { return asAlignItemsValue(value, key); } },
      direction: { key: "direction", propId: 2, valueKind: "enum", reset: "column", method: "setDirection", parseValue(value, key) { return asFlexDirectionValue(value, key); } },
      enabled: { key: "enabled", propId: 3, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      gap: { key: "gap", propId: 4, valueKind: "integer", reset: 0, method: "setGap", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      grow: { key: "grow", propId: 5, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 6, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      justifyContent: { key: "justifyContent", propId: 7, valueKind: "enum", reset: "flex-start", method: "setJustifyContent", parseValue(value, key) { return asJustifyContentValue(value, key); } },
      minHeight: { key: "minHeight", propId: 8, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 9, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      padding: { key: "padding", propId: 10, valueKind: "integer", reset: 0, method: "setPadding", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      shrink: { key: "shrink", propId: 11, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      title: { key: "title", propId: 12, valueKind: "string", method: "setTitle", parseValue(value, key) { return asString(value, key); } },
      width: { key: "width", propId: 13, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "label": {
    props: {
      enabled: { key: "enabled", propId: 1, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      family: { key: "family", propId: 2, valueKind: "string", method: "setFamily", parseValue(value, key) { return asString(value, key); } },
      grow: { key: "grow", propId: 3, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 4, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      italic: { key: "italic", propId: 5, valueKind: "boolean", reset: false, method: "setItalic", parseValue(value, key) { return asBoolean(value, key); } },
      minHeight: { key: "minHeight", propId: 6, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 7, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      pointSize: { key: "pointSize", propId: 8, valueKind: "number", reset: 12.0, method: "setPointSize", parseValue(value, key) { return asNonNegativeF64(value, key); } },
      shrink: { key: "shrink", propId: 9, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      text: { key: "text", propId: 10, valueKind: "string", method: "setText", parseValue(value, key) { return asString(value, key); } },
      weight: { key: "weight", propId: 11, valueKind: "integer", reset: 400, method: "setWeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 12, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "button": {
    props: {
      enabled: { key: "enabled", propId: 1, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      family: { key: "family", propId: 2, valueKind: "string", method: "setFamily", parseValue(value, key) { return asString(value, key); } },
      grow: { key: "grow", propId: 3, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 4, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      italic: { key: "italic", propId: 5, valueKind: "boolean", reset: false, method: "setItalic", parseValue(value, key) { return asBoolean(value, key); } },
      minHeight: { key: "minHeight", propId: 6, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 7, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      pointSize: { key: "pointSize", propId: 8, valueKind: "number", reset: 12.0, method: "setPointSize", parseValue(value, key) { return asNonNegativeF64(value, key); } },
      shrink: { key: "shrink", propId: 9, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      text: { key: "text", propId: 10, valueKind: "string", method: "setText", parseValue(value, key) { return asString(value, key); } },
      weight: { key: "weight", propId: 11, valueKind: "integer", reset: 400, method: "setWeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 12, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "canvas": {
    props: {
      enabled: { key: "enabled", propId: 1, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      grow: { key: "grow", propId: 2, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 3, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      minHeight: { key: "minHeight", propId: 4, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 5, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      shrink: { key: "shrink", propId: 6, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 7, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "input": {
    props: {
      autoFocus: { key: "autoFocus", propId: 1, valueKind: "boolean", reset: false, method: "setAutoFocus", parseValue(value, key) { return asBoolean(value, key); } },
      cursorPosition: { key: "cursorPosition", propId: 2, valueKind: "integer", method: "setCursorPosition", parseValue(value, key) { return asI32(value, key); } },
      enabled: { key: "enabled", propId: 3, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      family: { key: "family", propId: 4, valueKind: "string", method: "setFamily", parseValue(value, key) { return asString(value, key); } },
      focusPolicy: { key: "focusPolicy", propId: 5, valueKind: "enum", method: "setFocusPolicy", parseValue(value, key) { return asFocusPolicyValue(value, key); } },
      grow: { key: "grow", propId: 6, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 7, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      italic: { key: "italic", propId: 8, valueKind: "boolean", reset: false, method: "setItalic", parseValue(value, key) { return asBoolean(value, key); } },
      minHeight: { key: "minHeight", propId: 9, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 10, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      placeholder: { key: "placeholder", propId: 11, valueKind: "string", method: "setPlaceholder", parseValue(value, key) { return asString(value, key); } },
      pointSize: { key: "pointSize", propId: 12, valueKind: "number", reset: 12.0, method: "setPointSize", parseValue(value, key) { return asNonNegativeF64(value, key); } },
      selectionEnd: { key: "selectionEnd", propId: 13, valueKind: "integer", method: "setSelectionEnd", parseValue(value, key) { return asI32(value, key); } },
      selectionStart: { key: "selectionStart", propId: 14, valueKind: "integer", method: "setSelectionStart", parseValue(value, key) { return asI32(value, key); } },
      shrink: { key: "shrink", propId: 15, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      text: { key: "text", propId: 16, valueKind: "string", method: "setText", parseValue(value, key) { return asString(value, key); } },
      weight: { key: "weight", propId: 17, valueKind: "integer", reset: 400, method: "setWeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 18, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "check": {
    props: {
      checked: { key: "checked", propId: 1, valueKind: "boolean", reset: false, method: "setChecked", parseValue(value, key) { return asBoolean(value, key); } },
      enabled: { key: "enabled", propId: 2, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      family: { key: "family", propId: 3, valueKind: "string", method: "setFamily", parseValue(value, key) { return asString(value, key); } },
      grow: { key: "grow", propId: 4, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 5, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      italic: { key: "italic", propId: 6, valueKind: "boolean", reset: false, method: "setItalic", parseValue(value, key) { return asBoolean(value, key); } },
      minHeight: { key: "minHeight", propId: 7, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 8, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      pointSize: { key: "pointSize", propId: 9, valueKind: "number", reset: 12.0, method: "setPointSize", parseValue(value, key) { return asNonNegativeF64(value, key); } },
      shrink: { key: "shrink", propId: 10, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      text: { key: "text", propId: 11, valueKind: "string", method: "setText", parseValue(value, key) { return asString(value, key); } },
      weight: { key: "weight", propId: 12, valueKind: "integer", reset: 400, method: "setWeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 13, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "text": {
    props: {
      enabled: { key: "enabled", propId: 1, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      family: { key: "family", propId: 2, valueKind: "string", method: "setFamily", parseValue(value, key) { return asString(value, key); } },
      grow: { key: "grow", propId: 3, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 4, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      italic: { key: "italic", propId: 5, valueKind: "boolean", reset: false, method: "setItalic", parseValue(value, key) { return asBoolean(value, key); } },
      minHeight: { key: "minHeight", propId: 6, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 7, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      pointSize: { key: "pointSize", propId: 8, valueKind: "number", reset: 12.0, method: "setPointSize", parseValue(value, key) { return asNonNegativeF64(value, key); } },
      shrink: { key: "shrink", propId: 9, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      text: { key: "text", propId: 10, valueKind: "string", method: "setText", parseValue(value, key) { return asString(value, key); } },
      weight: { key: "weight", propId: 11, valueKind: "integer", reset: 400, method: "setWeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 12, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "slider": {
    props: {
      autoFocus: { key: "autoFocus", propId: 1, valueKind: "boolean", reset: false, method: "setAutoFocus", parseValue(value, key) { return asBoolean(value, key); } },
      enabled: { key: "enabled", propId: 2, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      focusPolicy: { key: "focusPolicy", propId: 3, valueKind: "enum", method: "setFocusPolicy", parseValue(value, key) { return asFocusPolicyValue(value, key); } },
      grow: { key: "grow", propId: 4, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 5, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      maximum: { key: "maximum", propId: 6, valueKind: "integer", reset: 100, method: "setMaximum", parseValue(value, key) { return asI32(value, key); } },
      minHeight: { key: "minHeight", propId: 7, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 8, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minimum: { key: "minimum", propId: 9, valueKind: "integer", reset: 0, method: "setMinimum", parseValue(value, key) { return asI32(value, key); } },
      pageStep: { key: "pageStep", propId: 10, valueKind: "integer", reset: 10, method: "setPageStep", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      shrink: { key: "shrink", propId: 11, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      step: { key: "step", propId: 12, valueKind: "integer", reset: 1, method: "setStep", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      value: { key: "value", propId: 13, valueKind: "integer", reset: 0, method: "setValue", parseValue(value, key) { return asI32(value, key); } },
      width: { key: "width", propId: 14, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "doubleSpinBox": {
    props: {
      autoFocus: { key: "autoFocus", propId: 1, valueKind: "boolean", reset: false, method: "setAutoFocus", parseValue(value, key) { return asBoolean(value, key); } },
      enabled: { key: "enabled", propId: 2, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      focusPolicy: { key: "focusPolicy", propId: 3, valueKind: "enum", method: "setFocusPolicy", parseValue(value, key) { return asFocusPolicyValue(value, key); } },
      grow: { key: "grow", propId: 4, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 5, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      maximum: { key: "maximum", propId: 6, valueKind: "number", reset: 100.0, method: "setMaximum", parseValue(value, key) { return asF64(value, key); } },
      minHeight: { key: "minHeight", propId: 7, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 8, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minimum: { key: "minimum", propId: 9, valueKind: "number", reset: 0.0, method: "setMinimum", parseValue(value, key) { return asF64(value, key); } },
      shrink: { key: "shrink", propId: 10, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      step: { key: "step", propId: 11, valueKind: "number", reset: 1.0, method: "setStep", parseValue(value, key) { return asNonNegativeF64(value, key); } },
      value: { key: "value", propId: 12, valueKind: "number", reset: 0.0, method: "setValue", parseValue(value, key) { return asF64(value, key); } },
      width: { key: "width", propId: 13, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
} satisfies Record<string, QtWidgetBinding>

export const qtWidgetEntityMap = {
  "window": QtWindow,
  "view": QtView,
  "group": QtGroup,
  "label": QtLabel,
  "button": QtButton,
  "canvas": QtCanvas,
  "input": QtInput,
  "check": QtCheck,
  "text": QtText,
  "slider": QtSlider,
  "doubleSpinBox": QtDoubleSpinBox,
} satisfies Record<string, QtWidgetEntityCtor>
