// Auto-generated by packages/core-native/crates/native/src/bin/generate_ts_bindings.rs. Do not edit.
import type { JSX as SolidJsx } from "solid-js"

export interface WindowIntrinsicProps {
  alignItems?: "flex-start" | "center" | "flex-end" | "stretch"
  alwaysOnTop?: boolean
  direction?: "column" | "row"
  enabled?: boolean
  frameless?: boolean
  gap?: number
  grow?: number
  height?: number
  justifyContent?: "flex-start" | "center" | "flex-end"
  minHeight?: number
  minWidth?: number
  nextFrameRequested?: boolean
  padding?: number
  shrink?: number
  tick?: boolean
  title?: string
  transparentBackground?: boolean
  visible?: boolean
  width?: number
  children?: SolidJsx.Element
  onCloseRequested?: () => void
}

export interface ViewIntrinsicProps {
  alignItems?: "flex-start" | "center" | "flex-end" | "stretch"
  direction?: "column" | "row"
  enabled?: boolean
  gap?: number
  grow?: number
  height?: number
  justifyContent?: "flex-start" | "center" | "flex-end"
  minHeight?: number
  minWidth?: number
  padding?: number
  shrink?: number
  width?: number
  children?: SolidJsx.Element
}

export interface GroupIntrinsicProps {
  alignItems?: "flex-start" | "center" | "flex-end" | "stretch"
  direction?: "column" | "row"
  enabled?: boolean
  gap?: number
  grow?: number
  height?: number
  justifyContent?: "flex-start" | "center" | "flex-end"
  minHeight?: number
  minWidth?: number
  padding?: number
  shrink?: number
  title?: string
  width?: number
  children?: SolidJsx.Element
}

export interface LabelIntrinsicProps {
  enabled?: boolean
  family?: string
  grow?: number
  height?: number
  italic?: boolean
  minHeight?: number
  minWidth?: number
  pointSize?: number
  shrink?: number
  text?: string
  weight?: number
  width?: number
  children?: SolidJsx.Element
}

export interface ButtonIntrinsicProps {
  enabled?: boolean
  family?: string
  grow?: number
  height?: number
  italic?: boolean
  minHeight?: number
  minWidth?: number
  pointSize?: number
  shrink?: number
  text?: string
  weight?: number
  width?: number
  children?: SolidJsx.Element
  onClicked?: () => void
}

export interface CanvasIntrinsicProps {
  enabled?: boolean
  grow?: number
  height?: number
  minHeight?: number
  minWidth?: number
  shrink?: number
  width?: number
}

export interface InputIntrinsicProps {
  autoFocus?: boolean
  cursorPosition?: number
  enabled?: boolean
  family?: string
  focusPolicy?: "no-focus" | "tab-focus" | "click-focus" | "strong-focus"
  grow?: number
  height?: number
  italic?: boolean
  minHeight?: number
  minWidth?: number
  placeholder?: string
  pointSize?: number
  selectionEnd?: number
  selectionStart?: number
  shrink?: number
  text?: string
  weight?: number
  width?: number
  onFocusIn?: () => void
  onFocusOut?: () => void
  onCursorPositionChanged?: (payload: { oldPosition: number; cursorPosition: number }) => void
  onSelectionChanged?: (payload: { selectionStart: number; selectionEnd: number }) => void
  onChanged?: (value: string) => void
  onTextChanged?: (value: string) => void
}

export interface CheckIntrinsicProps {
  checked?: boolean
  enabled?: boolean
  family?: string
  grow?: number
  height?: number
  italic?: boolean
  minHeight?: number
  minWidth?: number
  pointSize?: number
  shrink?: number
  text?: string
  weight?: number
  width?: number
  onToggled?: (value: boolean) => void
}

export interface TextIntrinsicProps {
  enabled?: boolean
  family?: string
  grow?: number
  height?: number
  italic?: boolean
  minHeight?: number
  minWidth?: number
  pointSize?: number
  shrink?: number
  text?: string
  weight?: number
  width?: number
  children?: SolidJsx.Element
}

export interface SliderIntrinsicProps {
  autoFocus?: boolean
  enabled?: boolean
  focusPolicy?: "no-focus" | "tab-focus" | "click-focus" | "strong-focus"
  grow?: number
  height?: number
  maximum?: number
  minHeight?: number
  minWidth?: number
  minimum?: number
  pageStep?: number
  shrink?: number
  step?: number
  value?: number
  width?: number
  onFocusIn?: () => void
  onFocusOut?: () => void
  onValueChanged?: (value: number) => void
}

export interface DoubleSpinBoxIntrinsicProps {
  autoFocus?: boolean
  enabled?: boolean
  focusPolicy?: "no-focus" | "tab-focus" | "click-focus" | "strong-focus"
  grow?: number
  height?: number
  maximum?: number
  minHeight?: number
  minWidth?: number
  minimum?: number
  shrink?: number
  step?: number
  value?: number
  width?: number
  onFocusIn?: () => void
  onFocusOut?: () => void
  onValueChanged?: (value: number) => void
}

export interface QtIntrinsicElements {
  window: WindowIntrinsicProps
  view: ViewIntrinsicProps
  group: GroupIntrinsicProps
  label: LabelIntrinsicProps
  button: ButtonIntrinsicProps
  canvas: CanvasIntrinsicProps
  input: InputIntrinsicProps
  check: CheckIntrinsicProps
  text: TextIntrinsicProps
  slider: SliderIntrinsicProps
  doubleSpinBox: DoubleSpinBoxIntrinsicProps
}
