/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function applyBannerEnabled(node: object, value: boolean): void

export declare function applyBannerFamily(node: object, value: string): void

export declare function applyBannerGrow(node: object, value: number): void

export declare function applyBannerHeight(node: object, value: number): void

export declare function applyBannerItalic(node: object, value: boolean): void

export declare function applyBannerMinHeight(node: object, value: number): void

export declare function applyBannerMinWidth(node: object, value: number): void

export declare function applyBannerPointSize(node: object, value: number): void

export declare function applyBannerShrink(node: object, value: number): void

export declare function applyBannerText(node: object, value: string): void

export declare function applyBannerWeight(node: object, value: number): void

export declare function applyBannerWidth(node: object, value: number): void

export declare function applySpinTriangleEnabled(node: object, value: boolean): void

export declare function applySpinTriangleHeight(node: object, value: number): void

export declare function applySpinTriangleMinHeight(node: object, value: number): void

export declare function applySpinTriangleMinWidth(node: object, value: number): void

export declare function applySpinTriangleWidth(node: object, value: number): void

export declare function createBannerNode(app: object): object

export declare function createSpinTriangleNode(app: object): object
