/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class QtApp {
  static start(onEvent: (arg: QtHostEvent) => unknown): QtApp
  shutdown(): void
  get root(): QtNode
  createTextNode(value: string): QtNode
  debugSnapshot(): QtDebugSnapshot
  __qtSolidCreateWidget(specKey: string): QtNode
  __qtSolidGetNode(nodeId: number): QtNode
}

export declare class QtButton {
  static create(app: QtApp): QtButton
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: NonNegativeF64): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: FontWeight): void
  setWidth(value: number): void
}

export declare class QtCanvas {
  static create(app: QtApp): QtCanvas
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setEnabled(value: boolean): void
  setGrow(value: number): void
  setHeight(value: number): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setShrink(value: number): void
  setWidth(value: number): void
}

export declare class QtCheck {
  static create(app: QtApp): QtCheck
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setChecked(value: boolean): void
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: NonNegativeF64): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: FontWeight): void
  setWidth(value: number): void
}

export declare class QtDoubleSpinBox {
  static create(app: QtApp): QtDoubleSpinBox
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setAutoFocus(value: boolean): void
  setEnabled(value: boolean): void
  setFocusPolicy(value: FocusPolicy): void
  setGrow(value: number): void
  setHeight(value: number): void
  setMaximum(value: number): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setMinimum(value: number): void
  setShrink(value: number): void
  setStep(value: NonNegativeF64): void
  setValue(value: number): void
  setWidth(value: number): void
}

export declare class QtGroup {
  static create(app: QtApp): QtGroup
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setAlignItems(value: AlignItems): void
  setDirection(value: FlexDirection): void
  setEnabled(value: boolean): void
  setGap(value: number): void
  setGrow(value: number): void
  setHeight(value: number): void
  setJustifyContent(value: JustifyContent): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPadding(value: number): void
  setShrink(value: number): void
  setTitle(value: string): void
  setWidth(value: number): void
}

export declare class QtInput {
  static create(app: QtApp): QtInput
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setAutoFocus(value: boolean): void
  setCursorPosition(value: number): void
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setFocusPolicy(value: FocusPolicy): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPlaceholder(value: string): void
  setPointSize(value: NonNegativeF64): void
  setSelectionEnd(value: number): void
  setSelectionStart(value: number): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: FontWeight): void
  setWidth(value: number): void
  focus(): void
  selectAll(): void
}

export declare class QtLabel {
  static create(app: QtApp): QtLabel
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: NonNegativeF64): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: FontWeight): void
  setWidth(value: number): void
}

export declare class QtNode {
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  __qtSolidApplyStringProp(propId: number, value: string): void
  __qtSolidApplyStringPropByName(jsName: string, value: string): void
  __qtSolidApplyBoolProp(propId: number, value: boolean): void
  __qtSolidApplyBoolPropByName(jsName: string, value: boolean): void
  __qtSolidApplyI32Prop(propId: number, value: number): void
  __qtSolidApplyI32PropByName(jsName: string, value: number): void
  __qtSolidApplyF64Prop(propId: number, value: number): void
  __qtSolidApplyF64PropByName(jsName: string, value: number): void
  __qtSolidApplyEnumProp(propId: number, value: string): void
  __qtSolidApplyEnumPropByName(jsName: string, value: string): void
  __qtSolidReadStringPropByName(jsName: string): string
  __qtSolidReadBoolPropByName(jsName: string): boolean
  __qtSolidReadI32PropByName(jsName: string): number
  __qtSolidReadF64PropByName(jsName: string): number
  __qtSolidRequestRepaint(): void
  __qtSolidRequestNextFrame(): void
  __qtSolidReadWindowFrameState(): QtWindowFrameState
  __qtSolidCaptureWidget(): QtWidgetCapture
}

export declare class QtSlider {
  static create(app: QtApp): QtSlider
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setAutoFocus(value: boolean): void
  setEnabled(value: boolean): void
  setFocusPolicy(value: FocusPolicy): void
  setGrow(value: number): void
  setHeight(value: number): void
  setMaximum(value: number): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setMinimum(value: number): void
  setPageStep(value: number): void
  setShrink(value: number): void
  setStep(value: number): void
  setValue(value: number): void
  setWidth(value: number): void
}

export declare class QtSpinTriangle {
  static create(app: QtApp): QtSpinTriangle
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setEnabled(value: boolean): void
  setHeight(value: number): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setWidth(value: number): void
}

export declare class QtText {
  static create(app: QtApp): QtText
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: NonNegativeF64): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: FontWeight): void
  setWidth(value: number): void
}

export declare class QtView {
  static create(app: QtApp): QtView
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setAlignItems(value: AlignItems): void
  setDirection(value: FlexDirection): void
  setEnabled(value: boolean): void
  setGap(value: number): void
  setGrow(value: number): void
  setHeight(value: number): void
  setJustifyContent(value: JustifyContent): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPadding(value: number): void
  setShrink(value: number): void
  setWidth(value: number): void
}

export declare class QtWindow {
  static create(app: QtApp): QtWindow
  __qtAttach(initialProps: Array<QtInitialProp>): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  setAlignItems(value: AlignItems): void
  setAlwaysOnTop(value: boolean): void
  setDirection(value: FlexDirection): void
  setEnabled(value: boolean): void
  setFrameless(value: boolean): void
  setGap(value: number): void
  setGrow(value: number): void
  setHeight(value: number): void
  setJustifyContent(value: JustifyContent): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setNextFrameRequested(value: boolean): void
  setPadding(value: number): void
  setShrink(value: number): void
  setTick(value: boolean): void
  setTitle(value: string): void
  setTransparentBackground(value: boolean): void
  setVisible(value: boolean): void
  setWidth(value: number): void
  getDeltaMs(): number
  getElapsedMs(): number
  getNextFrameRequested(): boolean
  getSeq(): number
}

export declare function __qtSolidDebugCaptureWindowFrame(windowId: number): QtWindowCaptureFrame

export declare function __qtSolidDebugClearHighlight(): void

export declare function __qtSolidDebugClickNode(nodeId: number): void

export declare function __qtSolidDebugCloseNode(nodeId: number): void

export declare function __qtSolidDebugEmitAppEvent(name: string): void

export declare function __qtSolidDebugGetNodeAtPoint(screenX: number, screenY: number): number | null

export declare function __qtSolidDebugGetNodeBounds(nodeId: number): QtDebugNodeBounds

export declare function __qtSolidDebugHighlightNode(nodeId: number): void

export declare function __qtSolidDebugInputInsertText(nodeId: number, value: string): void

export declare function __qtSolidDebugScheduleTimerEvent(delayMs: number, event: string): void

export declare function __qtSolidDebugSetInspectMode(enabled: boolean): void

export declare function __qtSolidTraceClear(): void

export declare function __qtSolidTraceEnterInteraction(traceId: number): void

export declare function __qtSolidTraceExitInteraction(): void

export declare function __qtSolidTraceRecordJs(traceId: number, stage: string, nodeId?: number | undefined | null, listenerId?: number | undefined | null, propId?: number | undefined | null, detail?: string | undefined | null): void

export declare function __qtSolidTraceSetEnabled(enabled: boolean): void

export declare function __qtSolidTraceSnapshot(): Array<QtTraceRecord>

export declare function __qtSolidWindowHostInfo(): QtWindowHostInfo

export declare const enum AlignItems {
  FlexStart = 'flex-start',
  Center = 'center',
  FlexEnd = 'flex-end',
  Stretch = 'stretch'
}

export declare const enum FlexDirection {
  Column = 'column',
  Row = 'row'
}

export declare const enum FocusPolicy {
  NoFocus = 'no-focus',
  TabFocus = 'tab-focus',
  ClickFocus = 'click-focus',
  StrongFocus = 'strong-focus'
}

export declare const enum JustifyContent {
  FlexStart = 'flex-start',
  Center = 'center',
  FlexEnd = 'flex-end'
}

export declare function ping(): string

export interface QtCapturedWidgetComposingPart {
  nodeId: number
  x: number
  y: number
  width: number
  height: number
  widthPx: number
  heightPx: number
  stride: number
  scaleFactor: number
  byteLength: number
}

export interface QtDebugNodeBounds {
  visible: boolean
  screenX: number
  screenY: number
  width: number
  height: number
}

export interface QtDebugNodeSnapshot {
  id: number
  kind: string
  parentId?: number
  children: Array<number>
  text?: string
  title?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  flexGrow?: number
  flexShrink?: number
  enabled?: boolean
  placeholder?: string
  checked?: boolean
  flexDirection?: FlexDirection
  justifyContent?: JustifyContent
  alignItems?: AlignItems
  gap?: number
  padding?: number
  value?: number
}

export interface QtDebugSnapshot {
  hostRuntime: string
  windowHostBackend?: string
  windowHostCapabilities?: QtWindowHostCapabilities
  rootId: number
  nodes: Array<QtDebugNodeSnapshot>
}

export type QtHostEvent =
  | { type: 'app', name: string }
  | { type: 'debug', name: string }
  | { type: 'inspect', nodeId: number }
  | { type: 'listener', nodeId: number, listenerId: number, traceId?: number, values: Array<QtListenerValue> }
  | { type: 'listenerbatch', nodeId: number, listenerIds: Array<number>, traceId?: number, values: Array<QtListenerValue> }

export interface QtInitialProp {
  key: string
  stringValue?: string
  boolValue?: boolean
  i32Value?: number
  f64Value?: number
}

export interface QtListenerValue {
  path: string
  kindTag: number
  stringValue?: string
  boolValue?: boolean
  i32Value?: number
  f64Value?: number
}

export interface QtTraceRecord {
  traceId: number
  tsUs: number
  lane: string
  stage: string
  nodeId?: number
  listenerId?: number
  propId?: number
  detail?: string
}

export interface QtWidgetCapture {
  format: QtWidgetCaptureFormat
  widthPx: number
  heightPx: number
  stride: number
  scaleFactor: number
  bytes: Buffer
}

export declare const enum QtWidgetCaptureFormat {
  Argb32Premultiplied = 'argb32-premultiplied',
  Rgba8Premultiplied = 'rgba8-premultiplied'
}

export interface QtWindowCaptureFrame {
  windowId: number
  grouping: QtWindowCaptureGrouping
  frameSeq: number
  elapsedMs: number
  deltaMs: number
  parts: Array<QtCapturedWidgetComposingPart>
}

export declare const enum QtWindowCaptureGrouping {
  Segmented = 'segmented',
  WholeWindow = 'whole-window'
}

export interface QtWindowFrameState {
  seq: number
  elapsedMs: number
  deltaMs: number
}

export interface QtWindowHostCapabilities {
  backendKind: string
  supportsZeroTimeoutPump: boolean
  supportsExternalWake: boolean
  supportsFdBridge: boolean
}

export interface QtWindowHostInfo {
  enabled: boolean
  backendName: string
  capabilities: QtWindowHostCapabilities
}
