// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
const __dirname = new URL('.', import.meta.url).pathname

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./index.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-android-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./index.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-android-arm-eabi')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./index.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-win32-x64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./index.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-win32-x64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./index.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-win32-ia32-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./index.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-win32-arm64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./index.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      return require('qt-solid-spike-darwin-universal')
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./index.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-darwin-x64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./index.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-darwin-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./index.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-freebsd-x64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./index.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-freebsd-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./index.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-x64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-x64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./index.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-arm64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-arm64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./index.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-arm-musleabihf')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-arm-gnueabihf')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./index.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-loong64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-loong64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./index.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-riscv64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./index.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('qt-solid-spike-linux-riscv64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./index.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-linux-ppc64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./index.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-linux-s390x-gnu')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./index.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-openharmony-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./index.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-openharmony-x64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./index.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('qt-solid-spike-openharmony-arm')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./index.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('qt-solid-spike-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

const { QtApp, QtNode, AlignItems, AlignSelf, canvasFragmentClearImage, canvasFragmentComputeLayout, canvasFragmentCreate, canvasFragmentDestroy, canvasFragmentDetachChild, canvasFragmentGetContentSize, canvasFragmentGetWorldBounds, canvasFragmentHitTest, canvasFragmentInsertChild, canvasFragmentRequestRepaint, canvasFragmentSetBoolProp, canvasFragmentSetDebugHighlight, canvasFragmentSetEncodedImage, canvasFragmentSetF64Prop, canvasFragmentSetLayoutFlip, canvasFragmentSetMotionTarget, canvasFragmentSetProp, canvasFragmentSetScrollOffset, canvasFragmentSetStringProp, canvasFragmentSnapshotAnimations, canvasFragmentSnapshotLayers, canvasFragmentStoreEnsure, canvasFragmentStoreRemove, canvasFragmentTreeSnapshot, captureCanvasRegion, captureCanvasSnapshot, captureFragmentIsolated, captureWindowFrame, clearHighlight, clickNode, clipboardClear, clipboardFormats, clipboardGet, clipboardGetText, clipboardHasText, clipboardSet, clipboardSetText, closeNode, emitAppEvent, FlexDirection, FlexWrap, FocusPolicy, focusWidget, FragmentBlendMode, getNodeAtPoint, getNodeBounds, getScreenGeometry, getWidgetSizeHint, highlightNode, inputInsertText, JustifyContent, measureText, QtTransitionType, QtWidgetCaptureFormat, QtWindowCaptureGrouping, scheduleTimerEvent, screenDpiInfo, setInspectMode, setWindowTransientOwner, showOpenFileDialog, showSaveFileDialog, systemColorScheme, traceClear, traceEnterInteraction, traceExitInteraction, traceRecordJs, traceSetEnabled, traceSnapshot, windowFullscreen, windowHostInfo, windowIsFullscreen, windowIsMaximized, windowIsMinimized, windowMaximize, windowMinimize, windowRestore } = nativeBinding
export { QtApp }
export { QtNode }
export { AlignItems }
export { AlignSelf }
export { canvasFragmentClearImage }
export { canvasFragmentComputeLayout }
export { canvasFragmentCreate }
export { canvasFragmentDestroy }
export { canvasFragmentDetachChild }
export { canvasFragmentGetContentSize }
export { canvasFragmentGetWorldBounds }
export { canvasFragmentHitTest }
export { canvasFragmentInsertChild }
export { canvasFragmentRequestRepaint }
export { canvasFragmentSetBoolProp }
export { canvasFragmentSetDebugHighlight }
export { canvasFragmentSetEncodedImage }
export { canvasFragmentSetF64Prop }
export { canvasFragmentSetLayoutFlip }
export { canvasFragmentSetMotionTarget }
export { canvasFragmentSetProp }
export { canvasFragmentSetScrollOffset }
export { canvasFragmentSetStringProp }
export { canvasFragmentSnapshotAnimations }
export { canvasFragmentSnapshotLayers }
export { canvasFragmentStoreEnsure }
export { canvasFragmentStoreRemove }
export { canvasFragmentTreeSnapshot }
export { captureCanvasRegion }
export { captureCanvasSnapshot }
export { captureFragmentIsolated }
export { captureWindowFrame }
export { clearHighlight }
export { clickNode }
export { clipboardClear }
export { clipboardFormats }
export { clipboardGet }
export { clipboardGetText }
export { clipboardHasText }
export { clipboardSet }
export { clipboardSetText }
export { closeNode }
export { emitAppEvent }
export { FlexDirection }
export { FlexWrap }
export { FocusPolicy }
export { focusWidget }
export { FragmentBlendMode }
export { getNodeAtPoint }
export { getNodeBounds }
export { getScreenGeometry }
export { getWidgetSizeHint }
export { highlightNode }
export { inputInsertText }
export { JustifyContent }
export { measureText }
export { QtTransitionType }
export { QtWidgetCaptureFormat }
export { QtWindowCaptureGrouping }
export { scheduleTimerEvent }
export { screenDpiInfo }
export { setInspectMode }
export { setWindowTransientOwner }
export { showOpenFileDialog }
export { showSaveFileDialog }
export { systemColorScheme }
export { traceClear }
export { traceEnterInteraction }
export { traceExitInteraction }
export { traceRecordJs }
export { traceSetEnabled }
export { traceSnapshot }
export { windowFullscreen }
export { windowHostInfo }
export { windowIsFullscreen }
export { windowIsMaximized }
export { windowIsMinimized }
export { windowMaximize }
export { windowMinimize }
export { windowRestore }
