/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class QtApp {
  static start(onEvent: (arg: QtHostEvent) => unknown): QtApp
  shutdown(): void
  get root(): QtNode
  debugSnapshot(): QtDebugSnapshot
  createWidget(): QtNode
  getNode(nodeId: number): QtNode
}

export declare class QtNode {
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
  wireEvent(exportId: number): void
  applyProp(update: WindowPropUpdate): void
  requestRepaint(): void
  requestNextFrame(): void
  readWindowFrameState(): QtWindowFrameState
  captureWidget(): QtWidgetCapture
}

export declare const enum AlignItems {
  FlexStart = 'flex-start',
  Center = 'center',
  FlexEnd = 'flex-end',
  Stretch = 'stretch'
}

export declare const enum AlignSelf {
  Auto = 'auto',
  FlexStart = 'flex-start',
  FlexEnd = 'flex-end',
  Center = 'center',
  Stretch = 'stretch'
}

export declare function canvasFragmentClearImage(canvasNodeId: number, fragmentId: number): void

export declare function canvasFragmentComputeLayout(canvasNodeId: number, availableWidth: number, availableHeight: number): void

export declare function canvasFragmentCreate(canvasNodeId: number, kind: string): number

export declare function canvasFragmentDestroy(canvasNodeId: number, fragmentId: number): void

export declare function canvasFragmentDetachChild(canvasNodeId: number, parentFragmentId: number, childFragmentId: number): void

export declare function canvasFragmentGetContentSize(canvasNodeId: number, fragmentId: number): QtWorldBounds | null

export declare function canvasFragmentGetWorldBounds(canvasNodeId: number, fragmentId: number): QtWorldBounds | null

export declare function canvasFragmentHitTest(canvasNodeId: number, x: number, y: number): number | null

export declare function canvasFragmentInsertChild(canvasNodeId: number, parentFragmentId: number, childFragmentId: number, beforeFragmentId?: number | undefined | null): void

export declare function canvasFragmentRequestRepaint(canvasNodeId: number): void

export declare function canvasFragmentSetBoolProp(canvasNodeId: number, fragmentId: number, key: string, value: boolean): void

export declare function canvasFragmentSetDebugHighlight(canvasNodeId: number, fragmentId?: number | undefined | null): void

export declare function canvasFragmentSetEncodedImage(canvasNodeId: number, fragmentId: number, data: Buffer): void

export declare function canvasFragmentSetF64Prop(canvasNodeId: number, fragmentId: number, key: string, value: number): void

export declare function canvasFragmentSetLayoutFlip(canvasNodeId: number, fragmentId: number, dx: number, dy: number, sx: number, sy: number, transition: QtTransitionSpec): boolean

export declare function canvasFragmentSetListener(canvasNodeId: number, fragmentId: number, listenerBit: number, enabled: boolean): void

export declare function canvasFragmentSetMotionTarget(canvasNodeId: number, fragmentId: number, target: QtMotionTarget, transition: QtPerPropertyTransition, delay?: number | undefined | null): boolean

export declare function canvasFragmentSetProp(canvasNodeId: number, fragmentId: number, key: string, value: FragmentValue): void

export declare function canvasFragmentSetScrollOffset(canvasNodeId: number, fragmentId: number, x: number, y: number): void

export declare function canvasFragmentSetStringProp(canvasNodeId: number, fragmentId: number, key: string, value: string): void

export declare function canvasFragmentSnapshotAnimations(canvasNodeId: number): Array<QtAnimationSnapshot>

export declare function canvasFragmentSnapshotLayers(canvasNodeId: number): Array<QtLayerSnapshot>

export declare function canvasFragmentStoreEnsure(canvasNodeId: number): void

export declare function canvasFragmentStoreRemove(canvasNodeId: number): void

export declare function canvasFragmentTreeSnapshot(canvasNodeId: number): Array<QtFragmentSnapshot>

export declare function captureCanvasRegion(canvasNodeId: number, x: number, y: number, width: number, height: number): Buffer | null

export declare function captureCanvasSnapshot(canvasNodeId: number): QtCanvasSnapshot | null

export declare function captureFragmentIsolated(canvasNodeId: number, fragmentId: number): Buffer | null

export declare function captureWindowFrame(windowId: number): QtWindowCaptureFrame

export declare function clearHighlight(): void

export declare function clickNode(nodeId: number): void

export declare function clipboardClear(): void

export interface ClipboardEntry {
  mime: string
  data: Buffer
}

export declare function clipboardFormats(): Array<string>

export declare function clipboardGet(mime: string): Buffer

export declare function clipboardGetText(): string

export declare function clipboardHasText(): boolean

export declare function clipboardSet(entries: Array<ClipboardEntry>): void

export declare function clipboardSetText(text: string): void

export declare function closeNode(nodeId: number): void

export declare function emitAppEvent(name: string): void

export declare const enum FlexDirection {
  Column = 'column',
  Row = 'row'
}

export declare const enum FlexWrap {
  Nowrap = 'nowrap',
  Wrap = 'wrap',
  WrapReverse = 'wrap-reverse'
}

export declare const enum FocusPolicy {
  NoFocus = 'no-focus',
  TabFocus = 'tab-focus',
  ClickFocus = 'click-focus',
  StrongFocus = 'strong-focus'
}

export declare function focusWidget(nodeId: number): void

export declare const enum FragmentBlendMode {
  Normal = 'normal',
  Multiply = 'multiply',
  Screen = 'screen',
  Overlay = 'overlay',
  Darken = 'darken',
  Lighten = 'lighten',
  ColorDodge = 'color-dodge',
  ColorBurn = 'color-burn',
  HardLight = 'hard-light',
  SoftLight = 'soft-light',
  Difference = 'difference',
  Exclusion = 'exclusion',
  Hue = 'hue',
  Saturation = 'saturation',
  Color = 'color',
  Luminosity = 'luminosity'
}

export interface FragmentTextRunWire {
  text: string
  fontSize: number
  fontFamily: string
  fontWeight: number
  fontItalic: boolean
  color: string
}

export type FragmentValue =
  | { type: 'f64', value: number }
  | { type: 'str', value: string }
  | { type: 'bool', value: boolean }
  | { type: 'lineargradient', startX: number, startY: number, endX: number, endY: number, stopOffsets: Array<number>, stopColors: Array<string> }
  | { type: 'radialgradient', centerX: number, centerY: number, radius: number, stopOffsets: Array<number>, stopColors: Array<string> }
  | { type: 'sweepgradient', centerX: number, centerY: number, startAngle: number, endAngle: number, stopOffsets: Array<number>, stopColors: Array<string> }
  | { type: 'boxshadow', offsetX: number, offsetY: number, blur: number, color: string, inset: boolean }
  | { type: 'textruns', runs: Array<FragmentTextRunWire> }
  | { type: 'radii', topLeft: number, topRight: number, bottomRight: number, bottomLeft: number }
  | { type: 'blendmode', value: FragmentBlendMode }
  | { type: 'unset' }

export declare function getNodeAtPoint(screenX: number, screenY: number): number | null

export declare function getNodeBounds(nodeId: number): QtDebugNodeBounds

export declare function getScreenGeometry(nodeId: number): QtScreenGeometryInfo

export declare function getWidgetSizeHint(nodeId: number): QtScreenGeometryInfo

export declare function highlightNode(nodeId: number): void

export declare function inputInsertText(nodeId: number, value: string): void

export declare const enum JustifyContent {
  FlexStart = 'flex-start',
  Center = 'center',
  FlexEnd = 'flex-end'
}

export declare function measureText(text: string, fontSize: number, fontFamily?: string | undefined | null, fontWeight?: number | undefined | null, fontItalic?: boolean | undefined | null, maxWidth?: number | undefined | null): TextMeasurement

export interface QtAnimationChannelSnapshot {
  property: string
  origin: number
  target: number
  state: string
}

export interface QtAnimationSnapshot {
  fragmentId: number
  tag: string
  channels: Array<QtAnimationChannelSnapshot>
}

export interface QtCanvasSnapshot {
  format: string
  widthPx: number
  heightPx: number
  stride: number
  scaleFactor: number
  bytes: Buffer
}

export interface QtCapturedWidgetComposingPart {
  nodeId: number
  x: number
  y: number
  width: number
  height: number
  widthPx: number
  heightPx: number
  stride: number
  scaleFactor: number
  byteLength: number
}

export interface QtDebugNodeBounds {
  visible: boolean
  screenX: number
  screenY: number
  width: number
  height: number
}

export interface QtDebugNodeSnapshot {
  id: number
  kind: string
  parentId?: number
  children: Array<number>
  text?: string
  title?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  flexGrow?: number
  flexShrink?: number
  enabled?: boolean
  placeholder?: string
  checked?: boolean
  flexDirection?: FlexDirection
  justifyContent?: JustifyContent
  alignItems?: AlignItems
  gap?: number
  padding?: number
  value?: number
}

export interface QtDebugSnapshot {
  hostRuntime: string
  windowHostBackend?: string
  windowHostCapabilities?: QtWindowHostCapabilities
  rootId: number
  nodes: Array<QtDebugNodeSnapshot>
}

export interface QtFragmentSnapshot {
  id: number
  tag: string
  parentId?: number
  childIds: Array<number>
  x: number
  y: number
  width: number
  height: number
  clip: boolean
  visible: boolean
  opacity: number
  props: Record<string, string>
}

export type QtHostEvent =
  | { type: 'app', name: string }
  | { type: 'debug', name: string }
  | { type: 'inspect', nodeId: number }
  | { type: 'listener', nodeId: number, listenerId: number, traceId?: number }
  | { type: 'canvaspointer', canvasNodeId: number, fragmentId: number, eventTag: number, x: number, y: number }
  | { type: 'canvaskeyboard', canvasNodeId: number, fragmentId: number, eventTag: number, qtKey: number, modifiers: number, text: string, repeat: boolean, nativeScanCode: number, nativeVirtualKey: number }
  | { type: 'canvaswheel', canvasNodeId: number, fragmentId: number, deltaX: number, deltaY: number, pixelDx: number, pixelDy: number, x: number, y: number, modifiers: number, phase: number }
  | { type: 'canvasmotioncomplete', canvasNodeId: number, fragmentId: number }
  | { type: 'canvasfocuschange', canvasNodeId: number, oldFragmentId: number, newFragmentId: number }
  | { type: 'canvastextinputchange', canvasNodeId: number, fragmentId: number, text: string, cursor: number, selStart: number, selEnd: number }
  | { type: 'fragmentlayout', canvasNodeId: number, fragmentId: number, x: number, y: number, width: number, height: number }
  | { type: 'windowfocuschange', nodeId: number, gained: boolean }
  | { type: 'windowresize', nodeId: number, width: number, height: number }
  | { type: 'windowstatechange', nodeId: number, state: number }
  | { type: 'colorschemechange', scheme: string }
  | { type: 'screendpichange', dpi: number }
  | { type: 'filedialogresult', requestId: number, paths: Array<string> }

export interface QtLayerSnapshot {
  fragmentId: number
  layerKey: number
  x: number
  y: number
  width: number
  height: number
  opacity: number
  reasons: string
}

export interface QtMotionTarget {
  x?: number
  y?: number
  scaleX?: number
  scaleY?: number
  rotate?: number
  opacity?: number
  originX?: number
  originY?: number
  xKeyframes?: Array<number>
  yKeyframes?: Array<number>
  scaleXKeyframes?: Array<number>
  scaleYKeyframes?: Array<number>
  rotateKeyframes?: Array<number>
  opacityKeyframes?: Array<number>
  originXKeyframes?: Array<number>
  originYKeyframes?: Array<number>
  backgroundR?: number
  backgroundG?: number
  backgroundB?: number
  backgroundA?: number
  borderRadius?: number
  blurRadius?: number
  shadowOffsetX?: number
  shadowOffsetY?: number
  shadowBlurRadius?: number
  shadowR?: number
  shadowG?: number
  shadowB?: number
  shadowA?: number
}

export interface QtPerPropertyTransition {
  default?: QtTransitionSpec
  x?: QtTransitionSpec
  y?: QtTransitionSpec
  scaleX?: QtTransitionSpec
  scaleY?: QtTransitionSpec
  rotate?: QtTransitionSpec
  opacity?: QtTransitionSpec
  originX?: QtTransitionSpec
  originY?: QtTransitionSpec
}

export interface QtScreenGeometryInfo {
  x: number
  y: number
  width: number
  height: number
}

export interface QtTraceRecord {
  traceId: number
  tsUs: number
  lane: string
  stage: string
  nodeId?: number
  listenerId?: number
  propId?: number
  detail?: string
}

export interface QtTransitionSpec {
  type: QtTransitionType
  duration?: number
  ease?: Array<number>
  stiffness?: number
  damping?: number
  mass?: number
  velocity?: number
  restDelta?: number
  restSpeed?: number
  repeat?: number
  repeatType?: string
  times?: Array<number>
}

export declare const enum QtTransitionType {
  Tween = 'tween',
  Spring = 'spring',
  Instant = 'instant'
}

export interface QtWidgetCapture {
  format: QtWidgetCaptureFormat
  widthPx: number
  heightPx: number
  stride: number
  scaleFactor: number
  bytes: Buffer
}

export declare const enum QtWidgetCaptureFormat {
  Argb32Premultiplied = 'argb32-premultiplied',
  Rgba8Premultiplied = 'rgba8-premultiplied'
}

export interface QtWindowCaptureFrame {
  windowId: number
  grouping: QtWindowCaptureGrouping
  frameSeq: number
  elapsedMs: number
  deltaMs: number
  parts: Array<QtCapturedWidgetComposingPart>
}

export declare const enum QtWindowCaptureGrouping {
  Segmented = 'segmented',
  WholeWindow = 'whole-window'
}

export interface QtWindowFrameState {
  seq: number
  elapsedMs: number
  deltaMs: number
}

export interface QtWindowHostCapabilities {
  backendKind: string
  supportsZeroTimeoutPump: boolean
  supportsExternalWake: boolean
  supportsFdBridge: boolean
}

export interface QtWindowHostInfo {
  enabled: boolean
  backendName: string
  capabilities: QtWindowHostCapabilities
}

export interface QtWorldBounds {
  x: number
  y: number
  width: number
  height: number
}

export declare function scheduleTimerEvent(delayMs: number, event: string): void

export declare function screenDpiInfo(id: number): ScreenDpiInfo

export interface ScreenDpiInfo {
  dpiX: number
  dpiY: number
  devicePixelRatio: number
  availableX: number
  availableY: number
  availableWidth: number
  availableHeight: number
}

export declare function setInspectMode(enabled: boolean): void

export declare function setWindowTransientOwner(windowId: number, ownerId: number): void

export declare function showOpenFileDialog(windowId: number, title: string, filter?: string | undefined | null, multiple?: boolean | undefined | null): number

export declare function showSaveFileDialog(windowId: number, title: string, filter?: string | undefined | null, defaultName?: string | undefined | null): number

export declare function systemColorScheme(): string

export interface TextMeasurement {
  width: number
  height: number
  ascent: number
  descent: number
  lineCount: number
}

export declare function traceClear(): void

export declare function traceEnterInteraction(traceId: number): void

export declare function traceExitInteraction(): void

export declare function traceRecordJs(traceId: number, stage: string, nodeId?: number | undefined | null, listenerId?: number | undefined | null, propId?: number | undefined | null, detail?: string | undefined | null): void

export declare function traceSetEnabled(enabled: boolean): void

export declare function traceSnapshot(): Array<QtTraceRecord>

export declare function windowFullscreen(id: number, enter: boolean): void

export declare function windowHostInfo(): QtWindowHostInfo

export declare function windowIsFullscreen(id: number): boolean

export declare function windowIsMaximized(id: number): boolean

export declare function windowIsMinimized(id: number): boolean

export declare function windowMaximize(id: number): void

export declare function windowMinimize(id: number): void

export type WindowPropUpdate =
  | { prop: 'title', value: string }
  | { prop: 'width', value: number }
  | { prop: 'height', value: number }
  | { prop: 'minWidth', value: number }
  | { prop: 'minHeight', value: number }
  | { prop: 'visible', value: boolean }
  | { prop: 'enabled', value: boolean }
  | { prop: 'frameless', value: boolean }
  | { prop: 'transparentBackground', value: boolean }
  | { prop: 'alwaysOnTop', value: boolean }
  | { prop: 'windowKind', value: number }
  | { prop: 'screenX', value: number }
  | { prop: 'screenY', value: number }
  | { prop: 'text', value: string }

export declare function windowRestore(id: number): void
