// Auto-generated by packages/core-native/crates/native/src/bin/generate_ts_bindings.rs. Do not edit.
import { readdirSync } from "node:fs"
import { createRequire } from "node:module"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import type { QtApp, QtNode } from "@qt-solid/core/native"

const require = createRequire(import.meta.url)

function resolveNativeDir(): string {
  try {
    const packageNativeEntry = require.resolve("@qt-solid/example-widgets/native")
    return join(dirname(packageNativeEntry), "../native")
  } catch {
    return join(dirname(fileURLToPath(import.meta.url)), "../native")
  }
}

const nativeDir = resolveNativeDir()

function isMusl() {
  if (process.platform !== "linux") {
    return false
  }

  try {
    return require("node:fs").readFileSync("/usr/bin/ldd", "utf8").includes("musl")
  } catch {
    return false
  }
}

function resolveNativeBinaryPath() {
  const entries = new Set(readdirSync(nativeDir))
  const candidates = []

  if (process.platform === "darwin") {
    candidates.push("index.darwin-universal.node")
    candidates.push(`index.darwin-${process.arch}.node`)
  } else if (process.platform === "linux") {
    const abi = isMusl() ? "musl" : "gnu"
    candidates.push(`index.linux-${process.arch}-${abi}.node`)
  } else if (process.platform === "win32") {
    candidates.push(`index.win32-${process.arch}-msvc.node`)
    candidates.push(`index.win32-${process.arch}-gnu.node`)
  } else if (process.platform === "freebsd") {
    candidates.push(`index.freebsd-${process.arch}.node`)
  } else if (process.platform === "android") {
    if (process.arch === "arm64") {
      candidates.push("index.android-arm64.node")
    } else if (process.arch === "arm") {
      candidates.push("index.android-arm-eabi.node")
    }
  }

  const match = candidates.find((candidate) => entries.has(candidate))
  if (!match) {
    throw new Error(
      `No native binary for ${process.platform}/${process.arch} under ${nativeDir}`,
    )
  }

  return join(nativeDir, match)
}

interface RawNativeBinding {
  createBannerNode(app: QtApp): QtNode
  applyBannerEnabled(node: QtNode, value: boolean): void
  applyBannerFamily(node: QtNode, value: string): void
  applyBannerGrow(node: QtNode, value: number): void
  applyBannerHeight(node: QtNode, value: number): void
  applyBannerItalic(node: QtNode, value: boolean): void
  applyBannerMinHeight(node: QtNode, value: number): void
  applyBannerMinWidth(node: QtNode, value: number): void
  applyBannerPointSize(node: QtNode, value: number): void
  applyBannerShrink(node: QtNode, value: number): void
  applyBannerText(node: QtNode, value: string): void
  applyBannerWeight(node: QtNode, value: number): void
  applyBannerWidth(node: QtNode, value: number): void
  createSpinTriangleNode(app: QtApp): QtNode
  applySpinTriangleEnabled(node: QtNode, value: boolean): void
  applySpinTriangleHeight(node: QtNode, value: number): void
  applySpinTriangleMinHeight(node: QtNode, value: number): void
  applySpinTriangleMinWidth(node: QtNode, value: number): void
  applySpinTriangleWidth(node: QtNode, value: number): void
}

const nativeBinding = require(resolveNativeBinaryPath()) as RawNativeBinding

      export class QtBanner {
        readonly #node: QtNode

        private constructor(node: QtNode) {
          this.#node = node
        }

        static create(app: QtApp): QtBanner {
          return new QtBanner(nativeBinding.createBannerNode(app))
        }

        get node(): QtNode {
          return this.#node
        }

        get id(): number {
          return this.#node.id
        }

        get parent(): QtNode | null {
          return this.#node.parent
        }

        get firstChild(): QtNode | null {
          return this.#node.firstChild
        }

        get nextSibling(): QtNode | null {
          return this.#node.nextSibling
        }

        isTextNode(): boolean {
          return this.#node.isTextNode()
        }

        insertChild(child: QtNode, anchor?: QtNode | undefined | null): void {
          this.#node.insertChild(child, anchor ?? null)
        }

        removeChild(child: QtNode): void {
          this.#node.removeChild(child)
        }

        destroy(): void {
          this.#node.destroy()
        }

        setEnabled(value: boolean): void {
  nativeBinding.applyBannerEnabled(this.#node, value)
}

setFamily(value: string): void {
  nativeBinding.applyBannerFamily(this.#node, value)
}

setGrow(value: number): void {
  nativeBinding.applyBannerGrow(this.#node, value)
}

setHeight(value: number): void {
  nativeBinding.applyBannerHeight(this.#node, value)
}

setItalic(value: boolean): void {
  nativeBinding.applyBannerItalic(this.#node, value)
}

setMinHeight(value: number): void {
  nativeBinding.applyBannerMinHeight(this.#node, value)
}

setMinWidth(value: number): void {
  nativeBinding.applyBannerMinWidth(this.#node, value)
}

setPointSize(value: number): void {
  nativeBinding.applyBannerPointSize(this.#node, value)
}

setShrink(value: number): void {
  nativeBinding.applyBannerShrink(this.#node, value)
}

setText(value: string): void {
  nativeBinding.applyBannerText(this.#node, value)
}

setWeight(value: number): void {
  nativeBinding.applyBannerWeight(this.#node, value)
}

setWidth(value: number): void {
  nativeBinding.applyBannerWidth(this.#node, value)
}
      }

      export class QtSpinTriangle {
        readonly #node: QtNode

        private constructor(node: QtNode) {
          this.#node = node
        }

        static create(app: QtApp): QtSpinTriangle {
          return new QtSpinTriangle(nativeBinding.createSpinTriangleNode(app))
        }

        get node(): QtNode {
          return this.#node
        }

        get id(): number {
          return this.#node.id
        }

        get parent(): QtNode | null {
          return this.#node.parent
        }

        get firstChild(): QtNode | null {
          return this.#node.firstChild
        }

        get nextSibling(): QtNode | null {
          return this.#node.nextSibling
        }

        isTextNode(): boolean {
          return this.#node.isTextNode()
        }

        insertChild(child: QtNode, anchor?: QtNode | undefined | null): void {
          this.#node.insertChild(child, anchor ?? null)
        }

        removeChild(child: QtNode): void {
          this.#node.removeChild(child)
        }

        destroy(): void {
          this.#node.destroy()
        }

        setEnabled(value: boolean): void {
  nativeBinding.applySpinTriangleEnabled(this.#node, value)
}

setHeight(value: number): void {
  nativeBinding.applySpinTriangleHeight(this.#node, value)
}

setMinHeight(value: number): void {
  nativeBinding.applySpinTriangleMinHeight(this.#node, value)
}

setMinWidth(value: number): void {
  nativeBinding.applySpinTriangleMinWidth(this.#node, value)
}

setWidth(value: number): void {
  nativeBinding.applySpinTriangleWidth(this.#node, value)
}
      }
