// Auto-generated by packages/core-native/crates/native/src/bin/generate_ts_bindings.rs. Do not edit.
import type { QtApp, QtInitialProp, QtNode } from "@qt-solid/core/native"

declare abstract class QtWidgetEntity {
  static create(app: QtApp): unknown
  __qtAttach?(initialProps: QtInitialProp[]): void
  get node(): QtNode
  get id(): number
  get parent(): QtNode | null
  get firstChild(): QtNode | null
  get nextSibling(): QtNode | null
  isTextNode(): boolean
  insertChild(child: QtNode, anchor?: QtNode | undefined | null): void
  removeChild(child: QtNode): void
  destroy(): void
}

export declare class QtBanner extends QtWidgetEntity {
  static create(app: QtApp): QtBanner
  setEnabled(value: boolean): void
  setFamily(value: string): void
  setGrow(value: number): void
  setHeight(value: number): void
  setItalic(value: boolean): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setPointSize(value: number): void
  setShrink(value: number): void
  setText(value: string): void
  setWeight(value: number): void
  setWidth(value: number): void
}

export declare class QtSpinTriangle extends QtWidgetEntity {
  static create(app: QtApp): QtSpinTriangle
  setEnabled(value: boolean): void
  setHeight(value: number): void
  setMinHeight(value: number): void
  setMinWidth(value: number): void
  setWidth(value: number): void
}
