// Auto-generated by packages/core-native/crates/native/src/bin/generate_ts_bindings.rs. Do not edit.

import type {
  QtApp,
  QtNode,
} from "@qt-solid/core/native"

import type {
  QtWidgetEntityCtor,
} from "@qt-solid/core/widget-library"

import {
  QtBanner,
  QtSpinTriangle,
} from "@qt-solid/example-widgets/native"

import {
  asBoolean,
  asF64,
  asI32,
  asNonNegativeF64,
  asNonNegativeI32,
  asString,
  createEnumValueParser,
  type EventExportSpec,
  type PropLeafBinding as SharedPropLeafBinding,
  type QtWidgetBinding as SharedQtWidgetBinding,
} from "@qt-solid/core/qt-host.shared"

export type PropMethodName = "setEnabled" | "setFamily" | "setGrow" | "setHeight" | "setItalic" | "setMinHeight" | "setMinWidth" | "setPointSize" | "setShrink" | "setText" | "setWeight" | "setWidth"

export type PropLeafBinding = SharedPropLeafBinding<PropMethodName>
export type QtWidgetBinding = SharedQtWidgetBinding<PropMethodName>

export const eventExportSpecs = {
} as const satisfies Record<string, EventExportSpec>

export const widgetBindings = {
  "banner": {
    props: {
      enabled: { key: "enabled", propId: 1, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      family: { key: "family", propId: 2, valueKind: "string", method: "setFamily", parseValue(value, key) { return asString(value, key); } },
      grow: { key: "grow", propId: 3, valueKind: "integer", reset: 0, method: "setGrow", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      height: { key: "height", propId: 4, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      italic: { key: "italic", propId: 5, valueKind: "boolean", reset: false, method: "setItalic", parseValue(value, key) { return asBoolean(value, key); } },
      minHeight: { key: "minHeight", propId: 6, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 7, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      pointSize: { key: "pointSize", propId: 8, valueKind: "number", reset: 12.0, method: "setPointSize", parseValue(value, key) { return asNonNegativeF64(value, key); } },
      shrink: { key: "shrink", propId: 9, valueKind: "integer", reset: 1, method: "setShrink", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      text: { key: "text", propId: 10, valueKind: "string", method: "setText", parseValue(value, key) { return asString(value, key); } },
      weight: { key: "weight", propId: 11, valueKind: "integer", reset: 400, method: "setWeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 12, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
  "spinTriangle": {
    props: {
      enabled: { key: "enabled", propId: 1, valueKind: "boolean", reset: true, method: "setEnabled", parseValue(value, key) { return asBoolean(value, key); } },
      height: { key: "height", propId: 2, valueKind: "integer", method: "setHeight", parseValue(value, key) { return asI32(value, key); } },
      minHeight: { key: "minHeight", propId: 3, valueKind: "integer", reset: 0, method: "setMinHeight", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      minWidth: { key: "minWidth", propId: 4, valueKind: "integer", reset: 0, method: "setMinWidth", parseValue(value, key) { return asNonNegativeI32(value, key); } },
      width: { key: "width", propId: 5, valueKind: "integer", method: "setWidth", parseValue(value, key) { return asI32(value, key); } },
    },
  },
} satisfies Record<string, QtWidgetBinding>

export const qtWidgetEntityMap = {
  "banner": QtBanner,
  "spinTriangle": QtSpinTriangle,
} satisfies Record<string, QtWidgetEntityCtor>
