// Auto-generated by packages/core-native/crates/native/src/bin/generate_ts_bindings.rs. Do not edit.
import type { JSX as SolidJsx } from "solid-js"

export interface BannerIntrinsicProps {
  enabled?: boolean
  family?: string
  grow?: number
  height?: number
  italic?: boolean
  minHeight?: number
  minWidth?: number
  pointSize?: number
  shrink?: number
  text?: string
  weight?: number
  width?: number
  children?: SolidJsx.Element
}

export interface SpinTriangleIntrinsicProps {
  enabled?: boolean
  height?: number
  minHeight?: number
  minWidth?: number
  width?: number
}

export interface QtIntrinsicElements {
  banner: BannerIntrinsicProps
  spinTriangle: SpinTriangleIntrinsicProps
}
